Help/urls.py
from django.urls import path

from . import views

# added pattern of contacts path
app_name = 'Help'
urlpatterns = [
    path('', views.index, name='Help'),
    path('thanks/', views.thanks, name = 'thanks')
]

django1/urls.py
#added path of contacts and binded it with urls
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path, re_path
urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    url(r'^', include('mainApp.urls')),
    path('contacts/', include('contacts.urls'), name="contacts"),
    path('help/', include('Help.urls')),
    path('news/', include('news.urls'), name = "news"),
    url(r'^api-auth/', include('rest_framework.urls')),
    path('', include('snippets.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

Help/models.py
from django.db import models

# Create your models here.

class Help(models.Model):

    first_name = models.CharField(max_length= 20)
    last_name = models.CharField(max_length=20)
    e_mail = models.EmailField(default="example@example.com")
    text = models.TextField(default=" ")

    def __str__(self):
        return self.first_name + ' ' + self.last_name

Help/forms.py
from django import forms

from .models import Help

class HelpForm(forms.ModelForm):

    class Meta:
        model = Help
        fields = ('first_name', 'last_name', 'e_mail', 'text')

Help/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .forms import HelpForm
from news.models import News


# Create your views here.
# added view for this
# def index(request):
#     return render(request, 'Help/index.html')

def index(request):

    if request.method == "POST":
        form = HelpForm(request.POST)
        if form.is_valid():
            post = form.save(commit = True)
            return redirect('/help/thanks')

    else:
        form = HelpForm()

    return render(request, 'Help/index.html', {'form' : form})

def thanks(request):

    return render(request, 'Help/thanks.html')

Help/templates/Help/index.html
{% extends "wrapper.html" %}

{% load staticfiles %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/helpform.css' %}">

    <div class = "text-center"><h2>Message to administration</h2></div>
    <form method="POST" class="post-form">{% csrf_token %}
            <div class="container">
                <tr><th><label for="id_first_name">First name:</label>
                </th><td><input type="text" name="first_name" maxlength="20" required id="id_first_name"  placeholder="Your name..."></td></tr>
                <tr><th><label for="id_last_name">Last name:</label>
                </th><td><input type="text" name="last_name" maxlength="20" required id="id_last_name" placeholder="Your last name..."></td></tr>
                <tr><th><label for="id_e_mail">E mail:</label>
                </th><td><input type="email" name="e_mail" value=" " maxlength="254" required id="id_e_mail" placeholder="Email..."></td></tr>
                <br>
                <tr><th><label for="id_text">Text:</label>
                </th><td><textarea name="text" cols="40" rows="10" required id="id_text" style="height:200px" placeholder="Write something.."></textarea></td></tr>

            <input type="submit" value="Submit">
            </div>
        </div>
    </form>
{% endblock %}

Help/templates/Help/thanks.html
{% extends "wrapper.html" %}

{% block content %}

<div class = "w3-display-container w3-display-middle">
    <h3>Thanks for your message</h3>
</div>

{% endblock content %}