Help/urls.py
from django.urls import path

from . import views

# added pattern of contacts path
app_name = 'Help'
urlpatterns = [
    path('', views.index, name='Help'),
    path('thanks/', views.thanks, name = 'thanks')
]

django1/urls.py
#added path of contacts and binded it with urls
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path, re_path
urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    url(r'^', include('mainApp.urls')),
    path('contacts/', include('contacts.urls'), name="contacts"),
    path('help/', include('Help.urls')),
    path('news/', include('news.urls'), name = "news"),
    url(r'^api-auth/', include('rest_framework.urls')),
    path('', include('snippets.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

news/urls.py
from django.urls import path

from . import views


app_name = 'news'
urlpatterns = [
    path('', views.main, name = 'newsmain'),
    path('<int:news_id>/', views.news_detail, name = 'detail')

]

news/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class News(models.Model):
    news_headline = models.CharField(max_length=200)
    news_body = models.CharField(max_length=1000, default=" ")
    news_published = models.DateTimeField('published date')

    def __str__(self):
        output = self.news_headline + " was published " + str(
            self.news_published) + " with text" + self.news_body
        return output

news/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import HttpResponse
from .models import News

# Create your views here.
def main(request):
    latest_news_list = News.objects.order_by('-news_published')
    context = {'latest_news_list': latest_news_list}
    return render(request, 'news/main.html', context)

def news_detail(request, news_id):
    news = get_object_or_404(News, pk= news_id)
    return render(request, 'news/detail.html', {'news': news})

news/templates/news/detail.html
{% extends 'wrapper.html' %}

{% block content %}
<div class = "container">
    <div class = "jumbotron">
        <p align="center">
            <h2>News headline:</h2>
            <h4>{{ news.news_headline }}</h4>
        <h5>News body:</h5>
        <p>
            {{ news.news_body }}
        </p>
       </p>

    </div>

</div>

{% endblock content %}

news/templates/news/main.html
<!DOCTYPE html>


{% extends "wrapper.html" %}
{% load staticfiles %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/img.css' %}">
    <img src="../static/mainAppIMG/trump.jpg" alt="Trump" class="center">
    <div class = "container">
        <div class = "jumbotron">
            <h3 class="display-5">Latest news </h3>
                {% if latest_news_list %}

                    {% for news in latest_news_list %}
                    <li>
                        <a href="{% url 'news:detail' news.id %}">{{ news.news_headline }}</a>
                    </li>
                {% endfor %}
                {% else %}
                    <h3>No news here</h3>
                {% endif %}
        </div>
    </div>
{% endblock content %}